public class Calculator {
    public void add(){
        integer a =10;
        integer b = 5;
        integer r = a+b;
        System.debug('add = ' + r);
    }
    public void subtract(){
        integer a =10;
        integer b = 5;
        integer r = a-b;
        System.debug('substract = ' + r);
    }
    public void multiply(){
        integer a =10;
        integer b = 5;
        integer r = a*b;
        System.debug('multiply = ' + r);
    }
    public void divide(){
        integer a =10;
        integer b = 5;
        integer r = a/b;
        System.debug('divide = ' + r);
    }
}